#!/bin/bash

pushd $(realpath $(dirname $0))/../bflibc;
make test --no-print-directory;
echo;
echo;

cd ../bflibcpp;
make test --no-print-directory;
echo;
echo;

cd ../bflibrust;
make test --no-print-directory;
echo;
echo;

cd ../bfnet;
make test --no-print-directory;
echo;
echo;

popd;

