name: BFLibC

on:
  push:
    branches: [ "features/dev/brando-improvedTests" ]
    paths:
      - 'bflibc/**'
  # pull_request:
  #   branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: test
      run: |
        cd bflibc;
        make dependencies
        make clean build CONFIG=test run

    - name: build
      run: |
        cd bflibc;
        make clean
        make build CONFIG=release
        make build CONFIG=debug

