name: BFNet

on:
  push:
    branches: [ "features/dev/brando-improvedTests" ]
  # pull_request:
  #   branches: [ "dev" ]

jobs:
  task:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: test
      run: |
        cd bfnet;
        make dependencies 
        make clean build CONFIG=test run

    - name: build
      run: |
        cd bfnet;
        make clean
        make build CONFIG=release
        make build CONFIG=debug

