name: C/C++ CI

on:
  push:
    branches: [ "patch/dev/brando-chatwork" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: test
      run: make clean test
    - name: make
      run: make clean all
