name: CI

on:
  push:
    branches: [ "dev" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "dev" ]
    paths-ignore:
      - '**.md'

jobs:
  unit-tests-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install uuid-dev
      run: sudo apt -y install uuid-dev
    - name: bftest
      run: |
        cd bftest;
        make clean build CONFIG=test run
    - name: bflibc
      run: |
        cd bflibc;
        make dependencies 
        make clean build CONFIG=test run
    - name: bflibcpp
      run: |
        cd bflibcpp;
        make dependencies 
        make clean build CONFIG=test run
    - name: bfnet
      run: |
        cd bfnet;
        make dependencies 
        make clean build CONFIG=test run

  unit-tests-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: bftest
      run: |
        cd bftest;
        make clean build CONFIG=test run
    - name: bflibc
      run: |
        cd bflibc;
        make dependencies 
        make clean build CONFIG=test run
    - name: bflibcpp
      run: |
        cd bflibcpp;
        make dependencies 
        make clean build CONFIG=test run
    - name: bfnet
      run: |
        cd bfnet;
        make dependencies 
        make clean build CONFIG=test run

